[project]
name = "philosophy-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.119.0",
    "nuitka>=2.8.9",
    "python-dotenv>=1.1.1",
    "requests>=2.32.5",
]
